bug fixes

diff --git a/devenv b/devenv
--- a/devenv
+++ b/devenv
@@ -17,13 +17,10 @@ alias du="du -h"
 alias update="sudo apt update; sudo apt upgrade -y"
 alias reload="[ -f ~/.d/rc ] && source ~/.d/rc || source ~/.bashrc"
 alias shutdown="shutdown now"
-alias ping="ping -c 4"
 alias tping="time ping"
-alias root="sudo -i"
 alias edit-a="nano ~/.d/alias"
 alias edit-p="nano ~/.d/prompt"
 alias edit-rc="[ -f ~/.d/rc ] && nano ~/.d/rc || nano ~/.bashrc"
-alias python="python3"
 alias ipkg="sudo apt install"
 
 ### Other aliases ###
@@ -31,6 +28,9 @@ alias ipkg="sudo apt install"
 alias reposync="__cwd=\\\`pwd\\\`; for repo in ~/repos/*; do cd \\\\\$repo; echo \\\"\\\\\$repo\\\" | rev | cut -d '/' -f1 | rev; pull; push; echo ' '; done; echo 'Repos up-to-date!'; cd \\\\\$__cwd; unset repo __cwd"
 alias pull="git pull"
 alias push="git push"
+
+# VENV
+alias de="deactivate"
 
 ### Rebound Aliases ###
 # Clear
@@ -42,17 +42,6 @@ alias clr="clear"
 # Remove and Copy
 alias rm="smart-rm"
 alias cp="smart-cp"
-
-### Conditional aliases ###
-if [[ \\\$USER == "root" && ! -e ~/.aliascopied ]]; then
-  read -p "Would you like to copy root aliases to a user directory? [Y/n] " yn
-  if [[ "\\\${yn,}" == "y" ]]; then
-    read -p "Enter username: " user
-    cp /root/.bash_aliases "/home/\\\${user,}/.bash_aliases"
-    touch /root/.aliascopied
-    echo "Copied aliases!"
-  fi
-fi
 A
 `
 __prompt=`cat <<-P
@@ -88,8 +77,7 @@ K
 
 __yn=`cat <<-Y
 #!/bin/bash
-read -p "\\\$1 " yn
-[[ "\\\${yn,}" == 'y' ]] && eval \\\$2 || eval \\\$3
+[[ ! "\\\$1" == "" && ! "\\\$2" == "" && ! "\\\$3" == "" ]] && ( read -p "\\\$1 " yn; [[ "\\\${yn,}" =~ 'y' ]] && eval \\\$2 || eval \\\$3 ) || echo "Cannot process yn context!"
 Y
 `
 
